# Generated by Django 4.2.9 on 2024-01-18 17:42

from django.db import migrations, models
import django.utils.timezone
import news.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("content_summary", models.TextField()),
                (
                    "scraped_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        validators=[news.models.validate_date_is_not_future],
                    ),
                ),
                ("source_site", models.CharField(default="UNKNOWN", max_length=64)),
                ("url_from", models.CharField(blank=True, max_length=256, null=True)),
                ("category", models.CharField(blank=True, max_length=64, null=True)),
                ("clickbait_decision_nlp", models.SmallIntegerField(default=-1)),
                ("clickbait_probability_nlp", models.FloatField(default=0)),
                ("clickbait_decision_llm", models.SmallIntegerField(default=-1)),
                ("clickbait_probability_llm", models.FloatField(default=0)),
                ("clickbait_decision_vertex", models.SmallIntegerField(default=-1)),
                ("clickbait_decision_final", models.SmallIntegerField(default=-1)),
            ],
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                check=models.Q(("clickbait_decision_nlp__in", [-1, 0, 1])),
                name="valid_decision_nlp",
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                check=models.Q(("clickbait_decision_llm__in", [-1, 0, 1])),
                name="valid_decision_llm",
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                check=models.Q(("clickbait_decision_vertex__in", [-1, 0, 1])),
                name="valid_decision_vertex",
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                check=models.Q(("clickbait_decision_final__in", [-1, 0, 1, 2, 3])),
                name="valid_decision_final",
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("clickbait_probability_nlp__gte", 0),
                    ("clickbait_probability_nlp__lte", 1),
                ),
                name="valid_probability_nlp",
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("clickbait_probability_llm__gte", 0),
                    ("clickbait_probability_llm__lte", 1),
                ),
                name="valid_probability_llm",
            ),
        ),
    ]
