# Generated by Django 4.2.6 on 2023-10-14 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="clickbait",
        ),
        migrations.AddField(
            model_name="article",
            name="clickbait_decision_LLM",
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="article",
            name="clickbait_decision_NLP",
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="article",
            name="clickbait_decision_final",
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="article",
            name="scraped_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="article",
            name="source_site",
            field=models.CharField(default="UNKNOWN", max_length=50),
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.CharField(max_length=50),
        ),
    ]
