# Generated by Django 4.2.6 on 2023-10-22 14:42

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import news.models


class Migration(migrations.Migration):
    replaces = [
        ("news", "0002_remove_article_published_date_not_later_than_tomorrow_and_more"),
        ("news", "0003_remove_article_published_date_not_later_than_tomorrow"),
        ("news", "0004_alter_article_pub_date_alter_article_scraped_date"),
        ("news", "0005_alter_article_pub_date_alter_article_scraped_date"),
    ]

    dependencies = [
        ("news", "0001_W3_DEPLOY"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="article",
            name="published_date_not_later_than_tomorrow",
        ),
        migrations.AlterField(
            model_name="article",
            name="pub_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                validators=[news.models.validate_date_is_not_future],
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="scraped_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                validators=[news.models.validate_date_is_not_future],
            ),
        ),
    ]
