# Generated by Django 4.2.6 on 2023-10-14 18:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_remove_article_clickbait_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="content",
            new_name="content_summary",
        ),
    ]
