# Generated by Django 4.2.6 on 2023-10-22 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_remove_article_published_date_not_later_than_tomorrow_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="article",
            name="published_date_not_later_than_tomorrow",
        ),
    ]
