# Generated by Django 4.2.6 on 2023-11-06 08:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_0002_dev"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="author",
        ),
        migrations.RemoveField(
            model_name="article",
            name="pub_date",
        ),
    ]
