# Generated by Django 4.2.6 on 2023-10-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_rename_content_article_content_summary"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                check=models.Q(("clickbait_decision_NLP__in", [-1, 0, 1])),
                name="valid_decision_NLP",
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                check=models.Q(("clickbait_decision_LLM__in", [-1, 0, 1])),
                name="valid_decision_LLM",
            ),
        ),
    ]
