# Generated by Django 4.2.6 on 2023-10-22 14:21

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import news.models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_remove_article_published_date_not_later_than_tomorrow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="pub_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(news.models.tomorrow)
                ],
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="scraped_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                validators=[
                    django.core.validators.MaxValueValidator(news.models.tomorrow)
                ],
            ),
        ),
    ]
