# Generated by Django 4.2.6 on 2023-12-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_remove_article_author_remove_article_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="clickbait_decision_VERTEX",
            field=models.SmallIntegerField(default=-1),
        ),
    ]
