# Generated by Django 4.2.6 on 2024-01-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_article_clickbait_decision_vertex"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="clickbait_probability_LLM",
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name="article",
            name="clickbait_probability_NLP",
            field=models.FloatField(default=-1),
        ),
    ]
