# Generated by Django 4.2.6 on 2023-10-14 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_alter_article_author_alter_article_pub_date_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("pub_date__isnull", True),
                    (
                        "pub_date__lte",
                        datetime.datetime(
                            2023,
                            10,
                            14,
                            18,
                            46,
                            6,
                            396604,
                            tzinfo=datetime.timezone.utc,
                        ),
                    ),
                    _connector="OR",
                ),
                name="scraped_date_not_more_than_1_day_after_published",
            ),
        ),
    ]
