# Generated by Django 4.2.9 on 2024-01-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_article_category_article_subcategory"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="article",
            name="valid_decision_NLP",
        ),
        migrations.RemoveConstraint(
            model_name="article",
            name="valid_decision_LLM",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="clickbait_decision_LLM",
            new_name="clickbait_decision_llm",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="clickbait_decision_NLP",
            new_name="clickbait_decision_nlp",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="clickbait_decision_VERTEX",
            new_name="clickbait_decision_vertex",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="clickbait_probability_LLM",
            new_name="clickbait_probability_llm",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="clickbait_probability_NLP",
            new_name="clickbait_probability_nlp",
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                check=models.Q(("clickbait_decision_nlp__in", [-1, 0, 1])),
                name="valid_decision_nlp",
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                check=models.Q(("clickbait_decision_llm__in", [-1, 0, 1])),
                name="valid_decision_llm",
            ),
        ),
    ]
