# Generated by Django 4.2.9 on 2024-01-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0007_remove_article_valid_decision_nlp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="subcategory",
        ),
        migrations.AlterField(
            model_name="article",
            name="clickbait_probability_llm",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="article",
            name="clickbait_probability_nlp",
            field=models.FloatField(default=0),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                check=models.Q(("clickbait_decision_vertex__in", [-1, 0, 1])),
                name="valid_decision_vertex",
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                check=models.Q(("clickbait_decision_final__in", [-1, 0, 1, 2, 3])),
                name="valid_decision_final",
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("clickbait_probability_nlp__gte", 0),
                    ("clickbait_probability_nlp__lte", 1),
                ),
                name="valid_probability_nlp",
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("clickbait_probability_llm__gte", 0),
                    ("clickbait_probability_llm__lte", 1),
                ),
                name="valid_probability_llm",
            ),
        ),
    ]
